(define (rand symbol)
 (let ((x random-int))
  (cond ((eq? symbol 'generate)
		 (lambda () (set! x (rand-update x))
		  			x))
   		((eq? symbol 'reset)
		 (lambda (y) (set! x y)
		  			 y))
		(else (error "Unknown option" symbol)))))
